name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # --- THIS IS THE NEW PART ---
      # This explicitly sets the token for dagshub.init() to find
      - name: Set DagsHub Token
        run: echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Ingestion Script
        run: python scripts/get_data.py

      - name: Run Data Preprocessing
        run: python src/preprocess.py

      - name: Run Model Training and Tuning
        run: python src/train.py

      - name: Register Best Model
        run: python src/register_best_model.py